action_gpt_config_path: "/workspace/ActionGPT/action_gpt/configs/models/action_gpt_config.yaml"
dataset_config_path: "/workspace/ActionGPT/action_gpt/configs/data/calvin.yaml"
dataloader_config:
  bs_per_gpu: 32
  workers_per_gpu: 4
  prefetch_factor: 2
rgb_preprocessor_config: 
  model_vision_type: "siglip"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true
training_config:
  num_epochs: 20
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 4
  save_epochs: 1
  save_steps: 10000
  save_path: "/workspace/ActionGPT/action_gpt/outputs/calvin_task_abc_d"
  resume_ckpt_path: null
  max_epoch: 10
  pred_binary_gripper_action: true